name: Build Project

on:
  push:
    paths:
      - 'source/**'
      - 'premake5.lua'

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "lua_threaded"
      BUILD_WINDOWS: "false"
      ARTIFACT_EXPIRE: "1"
      UPLOAD: "pterodactyl"
      PTERODACTYL_KEY: ${{secrets.PTERODACTYL_KEY}}
      PTERODACTYL_URL: ${{secrets.PTERODACTYL_URL}}
      PTERODACTYL_SERVER: ${{secrets.PTERODACTYL_SERVER}}