name: Build Project

on:
  workflow_dispatch:
  push:
    paths:
      - 'source/**'
      - 'premake5.lua'

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "lua_threaded"
      BUILD_WINDOWS: "false"
      ARTIFACT_EXPIRE: "1"
      UPLOAD: "pterodactyl"
    secrets: inherit

  test:
    needs: build
    uses: RaphaelIT7/gmod-lua-threaded/.github/workflows/testing.yml@main
    secrets: inherit