name: Last working & tested version

on:
  workflow_dispatch:
  push:
    path:
      - '_testing/trigger_shit.txt'

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "lua_threaded"
      BUILD_WINDOWS: "false"
      ARTIFACT_EXPIRE: "30"